server:
  port: 8081
spring:
  application:
    name: 
  rabbitmq:
    host: 
    username: 
    password: 
    port: 5672
    virtual-host: 
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: CORRELATED
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
